### ISSUE TITLE
RWS support please

### ISSUE THREAD

**Issue by kurdischerjapane** [Blaxar/rwx2blender#1]
why RWS not working? is also renderware

**Comment by Blaxar** [comment]
RWS is something quite different from RWX, despite both having ties to the RenderWare engine.

As mentioned in the README.md: this project is about the RenderWare scripts used by Active Worlds, which is an (old) 3D object format that stores geometry in a text form.

http://www.tnlc.com/rw/intro.html

Even if I (or someone else) were to support RWS at some point: it wouldn't be in this project anyway.
