### ISSUE TITLE
texture path error?

### ISSUE THREAD

**Issue by HGStone** [Blaxar/rwx2blender#2]
hello, i am not sure why i am having this error, maybe i am just being a dumdum?

Python: Traceback (most recent call last):
  File "C:\Users\hatch\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rwx2blender.py", line 781, in execute
    elif not os.path.isdir(texturepath):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _PropertyDeferred

location: <unknown location>:-1

this is my folder structure:

 Volume in drive C has no label.
 Volume Serial Number is CC48-A77E

 Directory of C:\Nomad1

07/25/2021  08:57 AM    <DIR>          .
07/25/2021  08:57 AM    <DIR>          ..
07/25/2021  08:57 AM    <DIR>          rwx
07/25/2021  08:57 AM    <DIR>          textures

**Comment by HGStone** [comment]
so i tried this with blender 2.91 and everything works.. thanks to some helpful people on discord that looked into the script and saw you had it working on 2.91

**Comment by Blaxar** [comment]
Hello, glad you could work it out :)

And yes: everything is (unfortunately) highly dependent on which version of Blender you are using.

Also: I don't know what your requirements are or what you aim to do at the end, but be aware that the current implementation is still in an alpha stage, and not the most advanced one either.

If you want a better implementation of something loading RWX files, I can also suggest using another implementation of mine which is [three-rwx-loader](https://github.com/Blaxar/three-rwx-loader): It's a `three.js` node module but it's way more advanced than `rwx2blender` currently is.

If you have the patience and the know-how around `three.js` and node: you may be able to wrap it in a small export script to get some more convenient format to work with in Blender, but I understand that jumping from Python and Blender to node and three.js is quite a big stretch, so I won't blame you if you don't :p

I'll refactor and update `rwx2blender` at some point to match the progress I've made on `three-rwx-loader`, but my focus is elsewhere at the moment :)
